# vim: set ft=yaml ts=2 expandtab:
---
sudo: required
dist: xenial
language: python
python: 2.7
env:
 global:
   - ANSIBLE_ROLE_NAME=mafalb.devicetree
   - CI=travis
   - ANSIBLE_FORCE_COLOR=1
matrix:
  include:
    - env:
        - ANSIBLE_VERSION=2.3
      addons:
        apt:
          sources:
            - sourceline: "ppa:ansible/ansible-2.3"
          packages:
            - ansible
    - env:
        - ANSIBLE_VERSION=2.4
      addons:
        apt:
          sources:
            - sourceline: "ppa:ansible/ansible-2.4"
          packages:
            - ansible
    - env:
        - ANSIBLE_VERSION=2.5
      addons:
        apt:
          sources:
            - sourceline: "ppa:ansible/ansible-2.5"
          packages:
            - ansible
    - env:
        - ANSIBLE_VERSION=2.6
      addons:
        apt:
          sources:
            - sourceline: "ppa:ansible/ansible-2.6"
          packages:
            - ansible
    - env:
        - ANSIBLE_VERSION=2.7
      addons:
        apt:
          sources:
            - sourceline: "ppa:ansible/ansible-2.7"
          packages:
            - ansible
    - env:
        - ANSIBLE_VERSION=2.8
      addons:
        apt:
          sources:
            - sourceline: "ppa:ansible/ansible-2.8"
          packages:
            - ansible
    - env:
        - ANSIBLE_VERSION=2.9
      addons:
        apt:
          sources:
            - sourceline: "ppa:ansible/ansible-2.9"
          packages:
            - ansible

before_install:

  # the packaged python-docker in xenial does not work
  - sudo -H pip install --upgrade pyOpenSSL
  - sudo -H pip install --upgrade cryptography
  - sudo -H pip install docker

  - sudo -H pip install ansible-lint
  - sudo -H pip install --user molecule
  - echo "myself ansible_connection=local ansible_become=true" | sudo tee /etc/ansible/hosts >/dev/null
  - export PATH="/root/.local/bin:$PATH"

script:
  - ansible-lint .
  - ansible-playbook -D tests/ansible_version.yml -t all,debug
  - cd tests
  - ansible-lint --force-color -v test.yml
  - ansible-playbook --become -D test.yml -C -t all,debug
  - ansible-playbook --become -D test.yml    -t all,debug
  - ansible-playbook --become -D test.yml    -t all,debug | tee /tmp/idempotence.tee
  - cd ..
  - molecule converge
  - "! grep -E 'ok=.*changed=[^0].*unreachable=.*failed=' /tmp/idempotence.tee"

...
